sensuapi:
  image: sstarcher/sensu
  command: api
  links:
    - rabbitmq
    - redis
sensuserver:
  image: sstarcher/sensu
  command: server
  links:
    - redis
    - rabbitmq
    - sensuapi:api
  volumes:
    - './server_checks.json:/etc/sensu/conf.d/server_checks.json:ro'
client:
  image: sstarcher/sensu
  command: client
  environment:
    CLIENT_SUBSCRIPTIONS: all,default,production
  links:
    - rabbitmq
  # ghetto hack to place some check binaries on the clients
  volumes:
    - './check-test1.sh:/usr/bin/check-test1.sh:ro'
uchiwa:
  image: uchiwa/uchiwa
  volumes:
    - './uchiwa.json:/config/config.json:ro'
  links:
    - sensuapi:api
  ports: ['80:3000']
redis:
  image: redis
rabbitmq:
  image: rabbitmq
